"""
Strategy Engine - Evaluates strategies using in-memory indicator state.
No database queries allowed in this module.
"""

from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from enum import Enum
import logging

from engine.state import get_state_manager, SymbolState
from engine.indicators import compute_indicators_for_symbol, IndicatorSet

logger = logging.getLogger(__name__)


class SignalType(Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass
class StrategySignal:
    """Signal generated by a strategy."""
    symbol: str
    strategy_name: str
    signal_type: SignalType
    confidence: float  # 0-100
    entry_price: float
    stop_loss: float
    target_price: float
    reason: str
    indicators_used: List[str]
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "symbol": self.symbol,
            "strategy_name": self.strategy_name,
            "signal_type": self.signal_type.value,
            "confidence": self.confidence,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "target_price": self.target_price,
            "reason": self.reason,
            "indicators_used": self.indicators_used
        }


class BaseStrategy:
    """
    Base class for all strategies.
    Strategies consume pre-computed indicators - NO database access.
    """
    name: str = "BaseStrategy"
    description: str = "Base strategy class"
    required_indicators: List[str] = []
    
    def evaluate(
        self,
        symbol: str,
        indicators: IndicatorSet,
        ltp: float
    ) -> Optional[StrategySignal]:
        """
        Evaluate strategy using pre-computed indicators.
        Returns signal if conditions are met, None otherwise.
        
        This method must be O(1) - no loops over historical data.
        """
        raise NotImplementedError


class RSIMeanReversionStrategy(BaseStrategy):
    """RSI Mean Reversion - Buy oversold, sell overbought."""
    name = "RSI Mean Reversion"
    description = "Buy when RSI < 30, sell when RSI > 70"
    required_indicators = ["rsi_14"]
    
    def evaluate(
        self,
        symbol: str,
        indicators: IndicatorSet,
        ltp: float
    ) -> Optional[StrategySignal]:
        rsi = indicators.rsi_14
        atr = indicators.atr_14 if indicators.atr_14 > 0 else ltp * 0.02
        
        if rsi < 30:
            return StrategySignal(
                symbol=symbol,
                strategy_name=self.name,
                signal_type=SignalType.BUY,
                confidence=min(95, 30 + (30 - rsi) * 2),
                entry_price=ltp,
                stop_loss=ltp - (2 * atr),
                target_price=ltp + (3 * atr),
                reason=f"RSI oversold at {rsi:.1f}",
                indicators_used=["rsi_14", "atr_14"]
            )
        elif rsi > 70:
            return StrategySignal(
                symbol=symbol,
                strategy_name=self.name,
                signal_type=SignalType.SELL,
                confidence=min(95, 30 + (rsi - 70) * 2),
                entry_price=ltp,
                stop_loss=ltp + (2 * atr),
                target_price=ltp - (3 * atr),
                reason=f"RSI overbought at {rsi:.1f}",
                indicators_used=["rsi_14", "atr_14"]
            )
        
        return None


class MACDCrossoverStrategy(BaseStrategy):
    """MACD Crossover - Buy on bullish cross, sell on bearish."""
    name = "MACD Crossover"
    description = "Trade MACD line crossing signal line"
    required_indicators = ["macd_line", "macd_signal", "macd_histogram"]
    
    def evaluate(
        self,
        symbol: str,
        indicators: IndicatorSet,
        ltp: float
    ) -> Optional[StrategySignal]:
        macd = indicators.macd_line
        signal = indicators.macd_signal
        hist = indicators.macd_histogram
        atr = indicators.atr_14 if indicators.atr_14 > 0 else ltp * 0.02
        
        # Bullish crossover (MACD crosses above signal)
        if hist > 0 and abs(hist) < abs(macd) * 0.1:  # Recent cross
            return StrategySignal(
                symbol=symbol,
                strategy_name=self.name,
                signal_type=SignalType.BUY,
                confidence=min(85, 50 + abs(hist) * 100),
                entry_price=ltp,
                stop_loss=ltp - (2 * atr),
                target_price=ltp + (3 * atr),
                reason=f"MACD bullish crossover, histogram: {hist:.4f}",
                indicators_used=["macd_line", "macd_signal", "macd_histogram"]
            )
        # Bearish crossover
        elif hist < 0 and abs(hist) < abs(macd) * 0.1:
            return StrategySignal(
                symbol=symbol,
                strategy_name=self.name,
                signal_type=SignalType.SELL,
                confidence=min(85, 50 + abs(hist) * 100),
                entry_price=ltp,
                stop_loss=ltp + (2 * atr),
                target_price=ltp - (3 * atr),
                reason=f"MACD bearish crossover, histogram: {hist:.4f}",
                indicators_used=["macd_line", "macd_signal", "macd_histogram"]
            )
        
        return None


class BollingerBounceStrategy(BaseStrategy):
    """Bollinger Bands Bounce - Trade reversals at bands."""
    name = "Bollinger Bounce"
    description = "Buy at lower band, sell at upper band"
    required_indicators = ["bollinger_upper", "bollinger_lower", "bollinger_middle"]
    
    def evaluate(
        self,
        symbol: str,
        indicators: IndicatorSet,
        ltp: float
    ) -> Optional[StrategySignal]:
        upper = indicators.bollinger_upper
        lower = indicators.bollinger_lower
        middle = indicators.bollinger_middle
        atr = indicators.atr_14 if indicators.atr_14 > 0 else ltp * 0.02
        
        # Price near lower band (potential bounce)
        if ltp <= lower * 1.01:
            return StrategySignal(
                symbol=symbol,
                strategy_name=self.name,
                signal_type=SignalType.BUY,
                confidence=75,
                entry_price=ltp,
                stop_loss=lower - atr,
                target_price=middle,
                reason=f"Price at lower Bollinger band ({lower:.2f})",
                indicators_used=["bollinger_lower", "bollinger_middle"]
            )
        # Price near upper band (potential reversal)
        elif ltp >= upper * 0.99:
            return StrategySignal(
                symbol=symbol,
                strategy_name=self.name,
                signal_type=SignalType.SELL,
                confidence=75,
                entry_price=ltp,
                stop_loss=upper + atr,
                target_price=middle,
                reason=f"Price at upper Bollinger band ({upper:.2f})",
                indicators_used=["bollinger_upper", "bollinger_middle"]
            )
        
        return None


class EMAStackStrategy(BaseStrategy):
    """EMA Stack - Trade aligned EMAs."""
    name = "EMA Stack"
    description = "Trade when 9 > 21 > 50 EMA (bullish) or reverse (bearish)"
    required_indicators = ["ema_9", "ema_21", "ema_50"]
    
    def evaluate(
        self,
        symbol: str,
        indicators: IndicatorSet,
        ltp: float
    ) -> Optional[StrategySignal]:
        ema9 = indicators.ema_9
        ema21 = indicators.ema_21
        ema50 = indicators.ema_50
        atr = indicators.atr_14 if indicators.atr_14 > 0 else ltp * 0.02
        
        # Bullish stack: 9 > 21 > 50 and price above all
        if ema9 > ema21 > ema50 and ltp > ema9:
            return StrategySignal(
                symbol=symbol,
                strategy_name=self.name,
                signal_type=SignalType.BUY,
                confidence=70,
                entry_price=ltp,
                stop_loss=ema21,
                target_price=ltp + (3 * atr),
                reason=f"Bullish EMA stack: 9({ema9:.0f}) > 21({ema21:.0f}) > 50({ema50:.0f})",
                indicators_used=["ema_9", "ema_21", "ema_50"]
            )
        # Bearish stack: 9 < 21 < 50 and price below all
        elif ema9 < ema21 < ema50 and ltp < ema9:
            return StrategySignal(
                symbol=symbol,
                strategy_name=self.name,
                signal_type=SignalType.SELL,
                confidence=70,
                entry_price=ltp,
                stop_loss=ema21,
                target_price=ltp - (3 * atr),
                reason=f"Bearish EMA stack: 9({ema9:.0f}) < 21({ema21:.0f}) < 50({ema50:.0f})",
                indicators_used=["ema_9", "ema_21", "ema_50"]
            )
        
        return None


# Strategy registry
STRATEGIES: Dict[str, BaseStrategy] = {
    "RSI Mean Reversion": RSIMeanReversionStrategy(),
    "MACD Crossover": MACDCrossoverStrategy(),
    "Bollinger Bounce": BollingerBounceStrategy(),
    "EMA Stack": EMAStackStrategy(),
}


def evaluate_all_strategies(
    symbol: str,
    interval: str = "1d"
) -> List[StrategySignal]:
    """
    Evaluate all registered strategies for a symbol.
    Uses in-memory indicators - O(1) per strategy.
    """
    signals = []
    
    # Get indicators (computed once, shared by all strategies)
    indicators = compute_indicators_for_symbol(symbol, interval)
    if not indicators:
        return signals
    
    # Get current price
    state_manager = get_state_manager()
    symbol_state = state_manager.get_symbol(symbol)
    if not symbol_state:
        return signals
    
    ltp = symbol_state.ltp
    
    # Evaluate each strategy
    for name, strategy in STRATEGIES.items():
        try:
            signal = strategy.evaluate(symbol, indicators, ltp)
            if signal:
                signals.append(signal)
        except Exception as e:
            logger.error(f"Strategy {name} failed for {symbol}: {e}")
    
    return signals


def get_registered_strategies() -> List[Dict[str, str]]:
    """Get list of registered strategies."""
    return [
        {"name": s.name, "description": s.description}
        for s in STRATEGIES.values()
    ]
