
import os
import psycopg2

# Get DB URL from env or default
DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://postgres:admin@quantai-postgres:5432/quantai")
if "+asyncpg" in DATABASE_URL:
    DATABASE_URL = DATABASE_URL.replace("+asyncpg", "")

def repair_identity():
    print(f"Connecting to {DATABASE_URL}")
    try:
        conn = psycopg2.connect(DATABASE_URL)
        cur = conn.cursor()
        
        print("\n--- Repairing Identity Column ---")
        
        # 1. Drop existing identity
        print("1. Dropping existing identity...")
        try:
            cur.execute("ALTER TABLE instrument_master ALTER COLUMN instrument_id DROP IDENTITY IF EXISTS")
        except Exception as e:
            print(f"   (Warning: {e})")
            conn.rollback()

        # 2. Add as GENERATED BY DEFAULT
        print("2. Setting GENERATED BY DEFAULT...")
        cur.execute("ALTER TABLE instrument_master ALTER COLUMN instrument_id ADD GENERATED BY DEFAULT AS IDENTITY")
        
        # 3. Sync Sequence
        print("3. Syncing sequence...")
        cur.execute("SELECT MAX(instrument_id) FROM instrument_master")
        max_id = cur.fetchone()[0] or 1
        print(f"   Max ID is {max_id}")
        
        seq_query = "SELECT setval(pg_get_serial_sequence('instrument_master', 'instrument_id'), %s)"
        cur.execute(seq_query, (max_id,))
        print("   Sequence synced.")

        conn.commit()
        conn.close()
        print("\nRepair completed successfully.")
        
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    repair_identity()
