"""
Bot Database Models

Persistence layer for signal bot run history and signal records.
Tables auto-create via SQLAlchemy Base.metadata.create_all().
"""

from sqlalchemy import (
    Column, Integer, String, Float, Text, Boolean, DateTime, JSON,
    ForeignKey, Index
)
from datetime import datetime
from database import Base


class BotRun(Base):
    """Stores metadata for each bot pipeline execution."""
    __tablename__ = "bot_run"

    id = Column(Integer, primary_key=True, autoincrement=True)
    run_id = Column(String(16), unique=True, nullable=False, index=True)
    status = Column(String(20), nullable=False, default="RUNNING")  # RUNNING, COMPLETED, ERROR
    market_trend = Column(JSON, nullable=True)       # {trend, ema_50, ema_200, momentum, last_close}
    summary = Column(JSON, nullable=True)             # {total_stocks_analyzed, total_signals, ...}
    started_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)
    error_message = Column(Text, nullable=True)
    triggered_by = Column(String(20), default="manual")  # manual, scheduler
    buy_count = Column(Integer, default=0)
    sell_count = Column(Integer, default=0)

    __table_args__ = (
        Index("idx_bot_run_started", "started_at"),
        {"extend_existing": True},
    )

    def __repr__(self):
        return f"<BotRun(run_id={self.run_id}, status={self.status}, signals={self.buy_count + self.sell_count})>"


class BotSignalRecord(Base):
    """Stores individual BUY/SELL signals generated by a bot run."""
    __tablename__ = "bot_signal"

    id = Column(Integer, primary_key=True, autoincrement=True)
    run_id = Column(String(16), ForeignKey("bot_run.run_id"), nullable=False, index=True)
    symbol = Column(String(50), nullable=False)
    signal_type = Column(String(4), nullable=False)  # BUY or SELL
    correlation = Column(Float, nullable=True)
    correlation_category = Column(String(10), nullable=True)
    price_change_pct = Column(Float, nullable=True)
    current_price = Column(Float, nullable=True)
    volatility_level = Column(String(10), nullable=True)
    volatility_atr = Column(Float, nullable=True)
    pcr_value = Column(Float, nullable=True)
    pcr_source = Column(String(20), nullable=True)
    conviction = Column(String(10), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        Index("idx_bot_signal_run", "run_id"),
        Index("idx_bot_signal_symbol", "symbol"),
        Index("idx_bot_signal_conviction", "conviction"),
        {"extend_existing": True},
    )

    def __repr__(self):
        return f"<BotSignalRecord({self.signal_type} {self.symbol} conviction={self.conviction})>"
