apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quantai.fullname" . }}-backend
  labels:
    {{- include "quantai.labels" . | nindent 4 }}
    component: backend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "quantai.selectorLabels" . | nindent 6 }}
      component: backend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "quantai.selectorLabels" . | nindent 8 }}
        component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /api/health/
              port: http
          readinessProbe:
            httpGet:
              path: /api/health/
              port: http
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}
