apiVersion: v1
kind: Service
metadata:
  name: {{ include "quantai.fullname" . }}-dragonfly
  labels:
    {{- include "quantai.labels" . | nindent 4 }}
    component: dragonfly
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    {{- include "quantai.selectorLabels" . | nindent 4 }}
    component: dragonfly
