apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quantai.fullname" . }}-frontend
  labels:
    {{- include "quantai.labels" . | nindent 4 }}
    component: frontend
spec:
  {{- if not .Values.autoscaling.frontend.enabled }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "quantai.selectorLabels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      labels:
        {{- include "quantai.selectorLabels" . | nindent 8 }}
        component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
