apiVersion: v1
kind: Service
metadata:
  name: {{ include "quantai.fullname" . }}-kafka
  labels:
    {{- include "quantai.labels" . | nindent 4 }}
    component: kafka
spec:
  type: ClusterIP
  ports:
    - name: plaintext
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: internal
      port: 29092
      targetPort: 29092
      protocol: TCP
    - name: controller
      port: 29093
      targetPort: 29093
      protocol: TCP
  selector:
    {{- include "quantai.selectorLabels" . | nindent 4 }}
    component: kafka
