apiVersion: v1
kind: Service
metadata:
  name: {{ include "quantai.fullname" . }}-market-feed
  labels:
    {{- include "quantai.labels" . | nindent 4 }}
    component: market-feed
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      protocol: TCP
  selector:
    {{- include "quantai.selectorLabels" . | nindent 4 }}
    component: market-feed
