apiVersion: v1
kind: Service
metadata:
  name: {{ include "quantai.fullname" . }}-pgbouncer
  labels:
    {{- include "quantai.labels" . | nindent 4 }}
    component: pgbouncer
spec:
  type: ClusterIP
  ports:
    - name: pgbouncer
      port: 6432
      targetPort: 6432
      protocol: TCP
  selector:
    {{- include "quantai.selectorLabels" . | nindent 4 }}
    component: pgbouncer
