/**
 * F&O Stocks Data Utility
 * Lists NSE stocks/indices that have derivatives available.
 */

export const FNO_STOCKS = new Set([
  // Nifty 50 - All have derivatives
  "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "HINDUNILVR", "ITC",
  "SBIN", "BHARTIARTL", "KOTAKBANK", "LT", "AXISBANK", "ASIANPAINT", "MARUTI",
  "BAJFINANCE", "TITAN", "SUNPHARMA", "ULTRACEMCO", "HCLTECH", "WIPRO",
  "NTPC", "POWERGRID", "JSWSTEEL", "M&M", "TATASTEEL", "ADANIENT", "ADANIPORTS",
  "ONGC", "BPCL", "COALINDIA", "GRASIM", "TECHM", "INDUSINDBK", "HINDALCO",
  "DRREDDY", "CIPLA", "DIVISLAB", "BRITANNIA", "APOLLOHOSP", "BAJAJFINSV",
  "NESTLEIND", "EICHERMOT", "HEROMOTOCO", "TATACONSUM", "SHRIRAMFIN", "BEL",
  "SBILIFE", "HDFCLIFE", "TRENT", "BAJAJ-AUTO",
  
  // Nifty Next 50 - F&O available
  "ABB", "ADANIGREEN", "AMBUJACEM", "AUROPHARMA", "BANKBARODA", "BERGEPAINT",
  "BOSCHLTD", "CANBK", "CHOLAFIN", "COLPAL", "DLF", "DABUR", "GAIL", "GODREJCP",
  "HAVELLS", "ICICIPRULI", "ICICIGI", "INDHOTEL", "INDUSTOWER", "JIOFIN",
  "JINDALSTEL", "LICI", "LUPIN", "MARICO", "MOTHERSON", "NAUKRI", "NHPC",
  "NMDC", "OBEROIRLTY", "OFSS", "PAGEIND", "PERSISTENT", "PETRONET", "PFC",
  "PIDILITIND", "PNB", "POLYCAB", "RECLTD", "SBICARD", "SHREECEM", "SIEMENS",
  "SRF", "TATAMOTORS", "TATAPOWER", "TORNTPHARM", "TVSMOTOR", "VEDL", "ZOMATO",
  
  // Other F&O stocks
  "ACC", "ALKEM", "ASHOKLEY", "ASTRAL", "AUBANK", "BANDHANBNK", "BATAINDIA",
  "BHEL", "BIOCON", "CANFINHOME", "COFORGE", "COROMANDEL", "CROMPTON",
  "CUB", "DALBHARAT", "DEEPAKNTR", "DIXON", "ESCORTS", "EXIDEIND",
  "FEDERALBNK", "FORTIS", "GLENMARK", "GMRINFRA", "GNFC", "GODREJPROP",
  "GRANULES", "GUJGASLTD", "HAL", "HDFCAMC", "HONAUT", "IDFCFIRSTB", "IEX",
  "INDIANB", "INDIGO", "IRCTC", "IRFC", "IGL", "JKCEMENT", "JSWENERGY",
  "JUBLFOOD", "KEI", "KPITTECH", "LAURUSLABS", "LICHSGFIN", "LTIM", "LTTS",
  "M&MFIN", "MANAPPURAM", "MCDOWELL-N", "MCX", "METROPOLIS", "MFSL", "MGL",
  "MPHASIS", "MUTHOOTFIN", "NAM-INDIA", "NATIONALUM", "NAVINFLUOR", "NBCC",
  "NCC", "OIL", "PAYTM", "PIIND", "POLYPLEX", "PRESTIGE", "PVRINOX",
  "RAIN", "RAMCOCEM", "RBLBANK", "RELAXO", "RVNL", "SAIL", "SJVN",
  "SONACOMS", "STAR", "SUNTV", "SYNGENE", "TATACHEM", "TATACOMM", "TATAELXSI",
  "TIINDIA", "TORNTPOWER", "TRIDENT", "UBL", "UJJIVANSFB", "UPL", "VBL",
  "VOLTAS", "YESBANK", "ZEEL", "ZYDUSLIFE",
  
  // Index derivatives & aliases
  "NIFTY", "BANKNIFTY", "FINNIFTY", "NIFTYNXT50", "NIFTY 50", "BANK NIFTY", "NIFTY BANK"
]);

export const isFOSymbol = (symbol: string): boolean => {
  if (!symbol) return false;
  const clean = symbol.toUpperCase().replace("NSE:", "").trim();
  return FNO_STOCKS.has(clean);
};
